const textArea =document.getElementById("textArea")

const genetateBtn = document.getElementById("btn")



quotes = [
    "Be yourself; everyone else is already taken. – Oscar Wilde",
    "In the middle of every difficulty lies opportunity. – Albert Einstein",
    "What we think, we become. – Buddha",
    "The journey of a thousand miles begins with one step. – Lao Tzu",
    "Life is what happens when you're busy making other plans. – John Lennon",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
    "Happiness is not something ready-made. It comes from your own actions. – Dalai Lama",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "Act as if what you do makes a difference. It does. – William James",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "Try not to become a man of success. Rather become a man of value. – Albert Einstein",
    "Strive not to be a success, but rather to be of value. – Albert Einstein",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Everything you can imagine is real. – Pablo Picasso",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Life is short, and it's up to you to make it sweet. – Sarah Louise Delany",
    "Dream big and dare to fail. – Norman Vaughan",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "The mind is everything. What you think you become. – Buddha",
    "Change your thoughts and you change your world. – Norman Vincent Peale",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
    "The purpose of our lives is to be happy. – Dalai Lama",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "You must be the change you wish to see in the world. – Mahatma Gandhi",
    "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
    "Do not let making a living prevent you from making a life. – John Wooden",
    "Turn your wounds into wisdom. – Oprah Winfrey",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "You can’t go back and change the beginning, but you can start where you are and change the ending. – C.S. Lewis",
    "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Opportunities don't happen, you create them. – Chris Grosser",
    "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. – Jim Rohn",
    "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
    "The secret of getting ahead is getting started. – Mark Twain",
    "Don’t wish it were easier. Wish you were better. – Jim Rohn",
    "Do one thing every day that scares you. – Eleanor Roosevelt",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    "All progress takes place outside the comfort zone. – Michael John Bobak",
    "If you genuinely want something, don’t wait for it—teach yourself to be impatient. – Gurbaksh Chahal",
    "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
    "A year from now you may wish you had started today. – Karen Lamb",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt",
    "Don’t count the days, make the days count. – Muhammad Ali",
    "Do what you feel in your heart to be right – for you’ll be criticized anyway. – Eleanor Roosevelt",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
    "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "Courage is grace under pressure. – Ernest Hemingway",
    "The best revenge is massive success. – Frank Sinatra",
    "Life isn’t about finding yourself. Life is about creating yourself. – George Bernard Shaw",
    "The harder you work for something, the greater you’ll feel when you achieve it. – Anonymous",
    "Push yourself, because no one else is going to do it for you. – Anonymous",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths. – Anonymous",
    "The key to success is to start before you are ready. – Marie Forleo",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "Don’t stop when you’re tired. Stop when you’re done. – Marilyn Monroe",
    "Work hard in silence, let your success be the noise. – Frank Ocean",
    "Don’t limit your challenges. Challenge your limits. – Anonymous",
    "The best view comes after the hardest climb. – Anonymous",
    "Dream it. Wish it. Do it. – Anonymous",
    "Little things make big days. – Anonymous",
    "It's going to be hard, but hard does not mean impossible. – Anonymous",
    "Sometimes later becomes never. Do it now. – Anonymous",
    "Great things never come from comfort zones. – Anonymous",
    "Wake up with determination. Go to bed with satisfaction. – Anonymous",
    "Do something today that your future self will thank you for. – Anonymous",
    "Don’t wait for opportunity. Create it. – Anonymous",
    "Be stronger than your excuses. – Anonymous",
    "Doubt kills more dreams than failure ever will. – Suzy Kassem",
    "Discipline is the bridge between goals and accomplishment. – Jim Rohn",
    "Motivation gets you going, but discipline keeps you growing. – John C. Maxwell",
    "Make each day your masterpiece. – John Wooden",
    "Act like you mean it, even if you don’t feel like it. – Mel Robbins",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "Energy and persistence conquer all things. – Benjamin Franklin",
    "Stay hungry. Stay foolish. – Steve Jobs",
    "Success is not in what you have, but who you are. – Bo Bennett",
    "Hustle in silence and let your success make the noise. – Anonymous",
    "Sometimes the people with the worst past create the best future. – Umar Ibn Al-Khattab",
    "Be the change that you wish to see in the world. – Mahatma Gandhi",
    "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do. – Anonymous",
    "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
    "Fear is temporary. Regret is forever. – Anonymous",
    "If not now, when? If not you, who? – Hillel the Elder",
    "Fall seven times, stand up eight. – Japanese Proverb",
    "If you’re going through hell, keep going. – Winston Churchill",
    "Big journeys begin with small steps. – Anonymous",
    "You only live once, but if you do it right, once is enough. – Mae West",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "Opportunities multiply as they are seized. – Sun Tzu",
    "A smooth sea never made a skilled sailor. – Franklin D. Roosevelt"
]

function generateQuote(){
    let index = Math.floor(Math.random()* quotes.length)
    console.log(index);
    
    let selectedQuote = quotes[index]
    textArea.textContent = selectedQuote;
}

genetateBtn.addEventListener('click',generateQuote)

